name: chatbot
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  mysql1: ^0.20.0
  mysql_client: ^0.0.27
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/loading.gif
    - lib/assets/img/robot.png
  fonts:
    - family: happy
      fonts:
        - asset:  lib/assets/fonts/HappyMemories.ttf
